server:
  port: 8080

ribbon:
  eureka:
    enabled: false

zuul:
  routes:
    routedservice:
      path: /routed/**
      url: http://localhost:8090/default
      alturl: http://localhost:8090/alternative

    simpleservice:
      path: /simple/**
      url: http://localhost:8090/simple
